# Generated by Django 4.2 on 2023-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gpm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_id', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('students', models.IntegerField()),
                ('school_address', models.TextField(max_length=200)),
            ],
        ),
    ]
